services:
  - type: web
    name: searxng-api
    env: docker
    repo: https://github.com/your-username/your-searxng-repo
    branch: main
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: SEARXNG_BASE_URL
        value: https://searxng-api.onrender.com/
      - key: INSTANCE_NAME
        value: my-searxng-instance
    healthCheckPath: /search?q=test&format=json
    autoDeploy: true
